// <auto-generated />
using Base.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Base.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190410190453_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Base.Api.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<int>("CuotasAlready");

                    b.Property<int>("CuotasPending");

                    b.Property<string>("CuotasQ");

                    b.Property<int>("CuotasVal");

                    b.Property<string>("Ends");

                    b.Property<double>("Monto");

                    b.Property<string>("Nombre");

                    b.Property<string>("Payment");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("Base.Api.Models.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("ApellidoGarante");

                    b.Property<string>("Celular");

                    b.Property<string>("CelularGar");

                    b.Property<string>("Correo");

                    b.Property<string>("CorreoGar");

                    b.Property<string>("Electoral");

                    b.Property<string>("Empresa");

                    b.Property<double>("Ingresos");

                    b.Property<string>("Nombre");

                    b.Property<string>("NombreGarante");

                    b.Property<double>("Sueldo");

                    b.Property<string>("Telefono");

                    b.Property<string>("TelefonoGar");

                    b.HasKey("Id");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("Base.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
